<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Blog::class => App\BlogFactory::class,
            App\Home::class => App\HomeFactory::class,
            App\LayoutBase::class => App\LayoutBaseFactory::class,
            App\OrmMiddleware::class => App\OrmMiddlewareFactory::class,
            App\Project::class => App\ProjectFactory::class,
            App\ShowCase::class => App\ShowCaseFactory::class,
            App\SiteInfo::class => App\SiteInfoFactory::class,
            Auth\Denied::class => Auth\DeniedFactory::class,
            Auth\Login::class => Auth\LoginFactory::class,
            Auth\Logout::class => Auth\LogoutFactory::class,
            Auth\NewGuest::class => Auth\NewGuestFactory::class,
            Auth\OrmAccess::class => Auth\OrmAccessFactory::class,
            Auth\Register::class => Auth\RegisterFactory::class,
            Auth\WhoAmI::class => Auth\WhoAmIFactory::class,
            Layout\Footer::class => Layout\FooterFactory::class,
            Layout\Info::class => Layout\InfoFactory::class,
            Layout\LinkItem::class => Layout\LinkItemFactory::class,
            Layout\Nav::class => Layout\NavFactory::class,
            Layout\NavItem::class => Layout\NavItemFactory::class,
        ],
    ],
];
